version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
      - ./sql/prompts.sql:/docker-entrypoint-initdb.d/prompts.sql
  # mcp-server-vector:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "6274:6274"
  #     - "6277:6277"
  #   depends_on:
  #     - postgres

volumes:
  pgdata3:
    driver: local
